### ISSUE TITLE
Simplify docker-compose process

### ISSUE THREAD

**Issue by joe94** [xmidt-org/xmidt#12]
Currently, the `deploy` package in this repo contains a detailed readme with the instructions on how to bring up a docker-compose cluster for `XMiDT`. While there may not be functional problems with it, we'd like to change the following:

1) Instead of requesting the user to build service images (`Talaria`, `Scytale`, `Petasos`, `Caduceus`, `Tr1d1um`) locally, simply pull existing images from our new docker hub repo:  https://hub.docker.com/u/xmidt

2) For the components where we need to build an image locally, clone repos inside the `/tmp` folder to keeps things tidy.

**Important notes:**
Remember to leverage the fact that both image pulling at step 1 and docker-compose leverage the `{service}_VERSION` environment variable (i.e. `TALARIA_VERSION=0.1.3`) to know which service image tag to use. 
Make this obvious in the way you setup your scripts such that when I want to upgrade the version of any service, it'll be dead simple to do it.

**Comment by uLan08** [comment]
I'd like to work on this.

**Comment by joe94** [comment]
@uLan08 Thanks for showing interest in helping out! Don't hesitate to show progress and ask clarifying questions!

**Comment by kcajmagic** [comment]
Closed in #15
