### ISSUE TITLE
Add release badges to README

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/xmidt#16]
In the list of services, there are badges for each one, but the release badge is missing.

For example, the caduceus badge can be found here:
https://github.com/xmidt-org/caduceus

**Comment by kristinaspring** [comment]
The server support libraries also need more badges. For example, the webpa-common repo has many more badges than those listed on the README:
https://github.com/xmidt-org/webpa-common#webpa-common

**Comment by kcajmagic** [comment]
Fixed in https://github.com/xmidt-org/xmidt/pull/19
