### ISSUE TITLE
Need help with a WebPA server installation

### ISSUE THREAD

**Issue by carthicsj** [xmidt-org/xmidt#3]
I am new to WebPA and am trying to install WebPA components on a single VM running CentOS 6.9. I have installed the following versions of components:

**talaria-0.1.1-169
caduceus-0.1.1-294
petasos-0.1.1-113
scytale-0.1.1-91
tr1d1um-0.1.1-272**

When I start the services using their default configurations, all services except tr1d1um fail to start. I don't have access to AWS services (SNS, SQS) in my lab. My goal is to experiment with WebPA REST API (configure, query) and notifications using devices simulated using parodus. I have referred to xmidt Wiki and have clarity on the architecture. Since the configurations for each of components is not documented, I am unable to progress with the installation. Any help to bring up the services is highly appreciated.

Following are the errors observed in the log:

**Talaria:** 
**[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x7af3c5]**

goroutine 1 [running]:
vendor/github.com/spf13/viper.(*Viper).AllKeys(0x0, 0x7, 0xc4201f9a20, 0x411f59)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1378 +0x45
vendor/github.com/spf13/viper.(*Viper).AllSettings(0x0, 0x4127a8)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1458 +0x51
vendor/github.com/spf13/viper.(*Viper).Unmarshal(0x0, 0xad86a0, 0xc4201ae840, 0xc42024a680, 0x13)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:738 +0x2f
vendor/github.com/Comcast/webpa-common/service/servicecfg.NewEnvironment(0xd16ae0, 0xc4201cfac0, 0xd16dc0, 0x0, 0x0, 0x0, 0xd16b60, 0xc42026a4d0)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/Comcast/webpa-common/service/servicecfg/environment.go:25 +0xd1
main.talaria(0xc42001e1c0, 0x1, 0x1, 0x0)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:120 +0xb28
main.main.func1(0xc420090058)
        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:170 +0x49
main.main()
        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:173 +0x22

**Caduceus:**
**Unable to initialize new caduceus sender wrapper: Linger must be positive.**

**Petasos:**
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x7cc245]**

goroutine 1 [running]:
vendor/github.com/spf13/viper.(*Viper).AllKeys(0x0, 0x7, 0xc420225af0, 0x411f59)
        /root/rpmbuild/BUILD/petasos-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1378 +0x45
vendor/github.com/spf13/viper.(*Viper).AllSettings(0x0, 0x4127a8)
        /root/rpmbuild/BUILD/petasos-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1458 +0x51
vendor/github.com/spf13/viper.(*Viper).Unmarshal(0x0, 0xa93fe0, 0xc4201646a0, 0xc42025b440, 0xc420225c28)
        /root/rpmbuild/BUILD/petasos-0.1.1/src/vendor/github.com/spf13/viper/viper.go:738 +0x2f
vendor/github.com/Comcast/webpa-common/service/servicecfg.NewEnvironment(0xcb8600, 0xc4201579c0, 0xcb8880, 0x0, 0x0, 0xcb8560, 0xc42025b440, 0xc420225eb8)
        /root/rpmbuild/BUILD/petasos-0.1.1/src/vendor/github.com/Comcast/webpa-common/service/servicecfg/environment.go:25 +0xd1
main.petasos(0xc42001e200, 0x1, 0x1, 0xc420090058)
        /root/rpmbuild/BUILD/petasos-0.1.1/src/petasos/petasos.go:67 +0x5ed
main.main()
        /root/rpmbuild/BUILD/petasos-0.1.1/src/petasos/petasos.go:125 +0x45

**Scytale:**
...
**{"error":"missing 'aws' key","level":"error","msg":"unable to create primary handler","ts":"2018-05-23T07:31:23.349334053Z"}**

**Comment by kristinaspring** [comment]
Hello,

Are you still having problems?

**Comment by kristinaspring** [comment]
Haven't received a response, so I'm closing this issue.
