### ISSUE TITLE
Add Themis to prometheus scraping

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/xmidt#31]
https://github.com/xmidt-org/xmidt/blob/ca41fb4167fca2e65b1ff3bce0b76a00e978fd37/deploy/docker-compose/docFiles/prometheus.yml#L20

I think we need to add themis information to the docker prometheus.  Need some input from @joe94.

**Comment by joe94** [comment]
Yup! I can add this as part of the argus PR if that works
