### ISSUE TITLE
Unable to build docker image for simulator

### ISSUE THREAD

**Issue by ashdua06** [xmidt-org/xmidt#46]
Facing issue on trying to build docker image of simulator . Getting below error on building the image

-- Checking for module 'libcurl'
--   Package 'libcurl', required by 'virtual:world', not found
**CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:58 (pkg_check_modules)**

-- Configuring incomplete, errors occurred!
See also "/build/aker/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cd /build &&     git clone https://github.com/Comcast/parodus2mockTr181.git &&     cd parodus2mockTr181 &&     mkdir build &&     cd build &&     cmake .. && make &&     cd /build &&     git clone https://github.com/Comcast/parodus.git &&     cd parodus &&     git checkout ad2d43b4f6e980a6cc1c1340fc82564104eb1dd8 &&     mkdir build &&     cd build &&     cmake .. && make &&     cd /build &&     git clone https://github.com/Comcast/aker.git &&     cd aker &&     mkdir build &&     cd build &&     cmake .. && make' returned a non-zero code: 1

**Comment by joe94** [comment]
@ashdua06, a workaround is adding:
```
git checkout cfb54022fa6e0ba70040e419d34655da955637b5 && \
```
below this line https://github.com/xmidt-org/xmidt/blob/master/simulator/Dockerfile#L23

It looks like the dependency on libcurl got introduced after https://github.com/xmidt-org/aker/commit/cfb54022fa6e0ba70040e419d34655da955637b5
