### ISSUE TITLE
No Service discovery is available in petasos after deployment using docker-compose

### ISSUE THREAD

**Issue by Sachin4403** [xmidt-org/xmidt#55]
Hi Team,

I am using [deploy.sh](https://github.com/xmidt-org/xmidt/blob/cad8710674f4c1934b6e515e2a5fd404fddb4986/deploy/docker-compose/deploy.sh) to deploy all the services in a local docker. but Petasos is using fixed talaria instance. ideally, it should be getting the talaria instances from the consul.

**Comment by Sachin4403** [comment]
# Another problem 
Tracing configuration is also missing in /etc/petasos/petasos.yaml file

**Comment by Sachin4403** [comment]
Hi @joe94,  any update on this?

**Comment by joe94** [comment]
Hey @Sachin4403, sorry for the late response! I've been busy with some internal tasks lately. 
Hmm, so the config I'm expecting you to see if this one https://github.com/xmidt-org/petasos/blob/main/deploy/packaging/petasos_spruce.yaml but you're saying that's not it? 🤔

**Comment by Sachin4403** [comment]
Hi @joe94,

Checked today, it is available in the `/etc/petasos/petasos.yaml`. Thanks for looking into it.
