### ISSUE TITLE
Current diagram is out of date.  

### ISSUE THREAD

**Issue by githubsands** [xmidt-org/xmidt#6]
Diagram [https://github.com/Comcast/xmidt/blob/master/diagrams/xmidt-architecture.ditaa] is out of date.  

1. ZooKeep Ensemble is no longer a component 
2. Scytale no longer communicates with communicate with a SNS.  
3. Include how caduceus subscribes to a SNS for the purpose of a upstream service publisher.

**Comment by kristinaspring** [comment]
@schmidtw should we just remove the diagram in this repo? since we have this here:
https://xmidt.io/docs/introduction/overview/

**Comment by joe94** [comment]
xmidt.io seems to be our source of truth (and is up to date) so closing ticket
