### ISSUE TITLE
docker-compose syntax wrong in deploy script

### ISSUE THREAD

**Issue by AravindHemachandran** [xmidt-org/xmidt#66]
https://github.com/xmidt-org/xmidt/blob/8fa9345df51be5450d3f0e40d844d7102324f578/deploy/docker-compose/deploy.sh#L22

"docker-compose" is the syntax to bring up the servers using the docker-compose.yml file.

**Comment by JC000** [comment]
`docker-compose` is the old CLI.  Modern versions of the `docker` CLI supports the `compose` sub-command.

Non-issue.

**Comment by AravindHemachandran** [comment]
Thank you for the clarification. I was running this in Linux with docker cli where the `compose` sub-command was not available at the time.
